### ISSUE TITLE
stacklight werkt niet

### ISSUE THREAD

**Issue by engineerWPI** [W-P-I/KCB#15]
indrukken van reset en hmi clear (niet reset knop)
Hmi silent alarm moet dan naar 0

**Comment by engineerWPI** [comment]
![image](https://user-images.githubusercontent.com/106513653/172803431-a01b3ebb-1eab-487a-b8ce-a818979d533f.png)

**Comment by engineerWPI** [comment]
stacklight werkt wel. dit heeft te maken met de faulthandler.

**Comment by tomreit1** [comment]
akkoord
