### ISSUE TITLE
in unsuspend moet roerwerk aanblijven

### ISSUE THREAD

**Issue by engineerWPI** [W-P-I/KCB#33]

**Comment by engineerWPI** [comment]
Deze start echt pas in idle. het lijkt wel of doet hij het in resetting maar het scherm is te langzaam.

**Comment by engineerWPI** [comment]
dit kun je zien door een afi voor idle te zetten dan gaat hij pas aan met starting.

**Comment by tomreit1** [comment]
Akkoord
